Sw 3590 switch langues 4
SaTT-Wallet/Frontend pull request #367
Opened 2023-06-23 11:33 UTC by MohamedRayenJmili

This pull request addresses the following changes:

Missing Translations: Added missing translations across the website to ensure a comprehensive and consistent user experience for international users.

Faulty Translations: Corrected inaccurate or faulty translations to improve the accuracy and clarity of the content.

Additional Change Requests: Identified and addressed other areas for improvement, including [describe additional change requests here].

Please review and merge this pull request to incorporate the proposed changes. Thorough testing has been conducted to ensure the modifications do not introduce any new issues. Thank you for your attention to this pull request.

2023-06-23 16:38 UTC, ksibisamir requested changes

2023-06-23 16:38 UTC, ksibisamir commented on src/app/cgu/cgu.component.html
> +      third-party sites, including socialNetworking sites. If you click on a
social Networking

2023-06-26 09:06 UTC, MohamedRayenJmili commented on src/app/cgu/cgu.component.html
> +      third-party sites, including socialNetworking sites. If you click on a
i changed "socialNetworking" to "social networking"

2023-06-26 10:22 UTC, ksibisamir approved these changes

2023-06-26 10:22 UTC, merged