SW-3593-switch-language-5
SaTT-Wallet/Frontend pull request #372
Opened 2023-06-26 15:56 UTC by MohamedRayenJmili

This pull request addresses the requested changes and introduces a language switch feature to enhance the user experience and expand accessibility in [Project Name].

Changes Made:

Integrated the requested modifications to improve the user interface and enhance functionality.
Utilized the progress made in the previous release "SW-3590-switch-language-4" to streamline the implementation process and expedite deployment.
Acknowledged that some changes were already implemented in "SW-3590-switch-language-4."
Noted that certain APIs could not be translated at this time and are pending integration.
Please review and provide feedback on the changes made. We appreciate your patience as we work towards a complete integration of the remaining APIs. Your input and suggestions are valuable in delivering an exceptional product.

Thank you.

2023-07-03 14:11 UTC, ksibisamir requested changes

2023-07-03 14:11 UTC, ksibisamir commented on src/assets/i18n/fr.json
> +  "faq_rep_1a": "SaTT est un jeton de publicité numérique qui facilite les transactions entre les créateurs de contenu et les annonceurs. En fin de compte, SaTT facilite des achats de publicité numér
SaTT est un jeton spécifique à la publicité en ligne qui simplifie les échanges entre les créateurs de contenu et les annonceurs. En simplifiant les achats de publicité numérique, SaTT permet des transactions plus rapides, moins coûteuses et plus sécurisées. Il convient de souligner que SaTT est utilisable sur la blockchain Ethereum.

2023-07-03 14:11 UTC, ksibisamir commented on src/assets/i18n/fr.json
> +  "faq_rep_1c": "et Binance Smart Chain",
"faq_rep_1c": "Contrat SaTT ERC20: 0xdf49c9f599a0a9049d97cff34d0c30e468987389"

2023-07-04 11:50 UTC, MohamedRayenJmili commented on src/assets/i18n/fr.json
> +  "faq_rep_1a": "SaTT est un jeton de publicité numérique qui facilite les transactions entre les créateurs de contenu et les annonceurs. En fin de compte, SaTT facilite des achats de publicité numér
Done

2023-07-04 11:52 UTC, ksibisamir approved these changes

2023-07-04 11:52 UTC, merged