Correcting translations
SaTT-Wallet/Frontend pull request #383
Opened 2023-07-05 14:37 UTC by MohamedRayenJmili

This pull request includes the following changes:

Adjusted the displays to accommodate both translations, specifically addressing the length variations between English and French.
Incorporated the requested changes from previous tickets.
These changes aim to improve the user experience by ensuring that button displays are optimized for both English and French translations, preventing text overlap and maintaining a clean interface.

Thank you for your review.

2023-07-06 11:04 UTC, skanderKha requested changes
There is some little details that should be modified, if you have any question feel free to reach me

2023-07-06 11:04 UTC, skanderKha commented on src/assets/i18n/fr.json
> +  "You-re-about-to-Send": "Vous allez envoyer",
" Vous êtes sur le point d'envoyer " is better

2023-07-06 11:04 UTC, skanderKha commented on src/assets/i18n/fr.json
> +  "goToNewWallet":"Aller à Nouveau portefeuille",
"Allez vers le nouveau portefeuille" is better

2023-07-06 11:04 UTC, skanderKha commented on src/assets/i18n/fr.json
> +  "searchToken":"Cherche de Tokens",
" rechercher un token " or " recherche de tokens "  the term " recherche " is more appropriate than cherche

2023-07-06 11:04 UTC, skanderKha commented on src/app/wallet/wallet.component.html
> +          ' Now you have the possibility to create your Tron ​​wallet. You Need to just enter your transactional password to create it'
can you please put this sentence with its translation in the json file inside a viarable eg : createTronWallet: <sentence here>

2023-07-06 11:04 UTC, skanderKha commented on src/app/wallet/wallet.component.css
> +  width: 50%;
duplication of width , can you check it please 2443 and 2450

2023-07-06 15:25 UTC, skanderKha commented
@MohamedRayenJmili  i made some comments on your change can you please check them and update the code thanks

2023-07-06 15:57 UTC, skanderKha approved these changes

2023-07-07 08:22 UTC, ksibisamir approved these changes

2023-07-07 08:22 UTC, merged